import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';

const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        signInFallbackRedirectUrl="/learn"
        signUpFallbackRedirectUrl="/learn"
        afterSignOutUrl="/"
      >
        <body className={font.className}>
          <Toaster />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
